const sideMenu=[
    {
        label:"Home",
        to:'/',
    },
    {
        label:"profile",
        to:"/profile",
        children:[
            {
                label:"Details",
                to:"/details",
                children:[
                    {
                    label:"location",
                    to:"/location",
                    },
                ],
            },
        ],
    },
    {
        label:"Settings",
        to:"/settings",
        children:[
            {
                label:"Account",
                to:"account",
            },
            {
                label:"Security",
                to:"/security",
                children:[
                    {
                        label:"Login",
                        to:"/login",
                    },
                    {
                        label:"Register",
                        to:"/register",
                        children:[
                            {
                                label:"username",
                                to:"/username",
                            },
                            {
                                label:"password",
                                to:"/password",
                            }
                        ]
                    },
                    
                ],
            },
        ],
    },
]

export default sideMenu;